// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function CreateRunbook(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateRunbook'](arg1, arg2, arg3, arg4);
}

export function DeleteRunbook(arg1, arg2) {
  return window['go']['main']['App']['DeleteRunbook'](arg1, arg2);
}

export function ForgetEverything() {
  return window['go']['main']['App']['ForgetEverything']();
}

export function GenerateRunbookDraft(arg1, arg2) {
  return window['go']['main']['App']['GenerateRunbookDraft'](arg1, arg2);
}

export function GenerateTypedLogDraft(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateTypedLogDraft'](arg1, arg2, arg3, arg4);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConnectionSettings() {
  return window['go']['main']['App']['GetConnectionSettings']();
}

export function GetPublishedContent(arg1) {
  return window['go']['main']['App']['GetPublishedContent'](arg1);
}

export function GetRunbookDetail(arg1) {
  return window['go']['main']['App']['GetRunbookDetail'](arg1);
}

export function IsConnectionConfigured() {
  return window['go']['main']['App']['IsConnectionConfigured']();
}

export function ListActiveRunbooks() {
  return window['go']['main']['App']['ListActiveRunbooks']();
}

export function ListDomainFunctions() {
  return window['go']['main']['App']['ListDomainFunctions']();
}

export function ListPublishedMine() {
  return window['go']['main']['App']['ListPublishedMine']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PickCAFile() {
  return window['go']['main']['App']['PickCAFile']();
}

export function PublishRunbook(arg1, arg2) {
  return window['go']['main']['App']['PublishRunbook'](arg1, arg2);
}

export function RetryRunbook(arg1) {
  return window['go']['main']['App']['RetryRunbook'](arg1);
}

export function ReviseRunbook(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReviseRunbook'](arg1, arg2, arg3);
}

export function SaveConnectionSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveConnectionSettings'](arg1, arg2);
}
