// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthStatus():Promise<main.Identity>;

export function CreateRunbook(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.RunbookRow>;

export function DeleteRunbook(arg1:string,arg2:boolean):Promise<void>;

export function ForgetEverything():Promise<void>;

export function GenerateRunbookDraft(arg1:string,arg2:Array<string>):Promise<string>;

export function GenerateTypedLogDraft(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetConnectionSettings():Promise<main.ConnectionSettings>;

export function GetPublishedContent(arg1:string):Promise<main.PublishedRunbookContent>;

export function GetRunbookDetail(arg1:string):Promise<main.RunbookDetail>;

export function IsConnectionConfigured():Promise<boolean>;

export function ListActiveRunbooks():Promise<Array<main.RunbookRow>>;

export function ListDomainFunctions():Promise<Array<string>>;

export function ListPublishedMine():Promise<Array<main.PublishedRunbookSummary>>;

export function Login(arg1:string):Promise<main.Identity>;

export function Logout():Promise<void>;

export function PickCAFile():Promise<string>;

export function PublishRunbook(arg1:string,arg2:string):Promise<main.RunbookRow>;

export function RetryRunbook(arg1:string):Promise<main.RunbookRow>;

export function ReviseRunbook(arg1:string,arg2:string,arg3:string):Promise<main.RunbookRow>;

export function SaveConnectionSettings(arg1:string,arg2:string):Promise<void>;
