[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lucien-secret-scanner"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "fastapi==0.116.1",
  "uvicorn[standard]==0.35.0",
]

[tool.setuptools.packages.find]
include = ["app*"]

[project.optional-dependencies]
test = [
  "pytest==8.4.1",
  "pytest-asyncio==1.0.0",
]
